version: '3.8'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/cockroachdb:/cockroach/cockroach-data"